# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_data', '0002_auto_20170507_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='possibleAnswerA',
            new_name='incorrectAnswer1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='possibleAnswerB',
            new_name='incorrectAnswer2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='possibleAnswerC',
            new_name='incorrectAnswer3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='possibleAnswerD',
        ),
    ]
