# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_data', '0003_auto_20170508_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctAnswer',
            field=models.CharField(max_length=255),
        ),
    ]
