# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_data', '0004_auto_20170508_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
