# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_data', '0005_remove_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default='damen', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.CharField(default='damen', max_length=255),
            preserve_default=False,
        ),
    ]
